[build]
  publish = "dist/joshua-shalim-portfolio/browser"
  command = "ng build --configuration static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
